import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually
  notes: [
    {
      label: 'Javascript',
      type: 'category',
      link: { type: 'generated-index' },
      items: [
        {
          label: 'Javascript高级程序设计',
          type: 'category',
          link: { type: 'generated-index' },
          items: [
            {
              type: 'autogenerated',
              dirName: 'notes/javascript/JavaScript高级程序设计',
            },
          ],
        },
        {
          label: 'JavaScript工程师都应懂的33个概念',
          type: 'category',
          link: { type: 'generated-index' },
          items: [
            {
              type: 'autogenerated',
              dirName: 'notes/javascript/JavaScript工程师都应懂的33个概念',
            },
          ],
        },
        {
          label: '【面向学习】',
          type: 'category',
          link: { type: 'generated-index' },
          items: [
            {
              type: 'autogenerated',
              dirName: 'notes/javascript/【面向学习】',
            },
          ],
        },
        'notes/javascript/javascript-test',
        'notes/javascript/javascript-test1',
      ]
    },
  ],
}

export default sidebars;
